# Generated by Django 2.2.1 on 2019-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique_for_month=True)),
                ('month', models.DateField()),
                ('mo_return', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
