# Generated by Django 2.2.1 on 2019-05-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20190512_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='mo_return',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
