# Generated by Django 2.2.1 on 2019-05-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20190512_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='month',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='index',
            unique_together={('name', 'date')},
        ),
    ]
