# Generated by Django 2.2.1 on 2019-05-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20190512_2327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='index',
            unique_together=set(),
        ),
    ]
