# Generated by Django 2.2.1 on 2019-05-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20190512_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='name',
            new_name='index_name',
        ),
    ]
