# Generated by Django 2.2.1 on 2019-05-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20190514_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='index_name',
            field=models.CharField(max_length=50),
        ),
    ]
